version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelab-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - homelab-network
    depends_on:
      - db
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: homelab-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - homelab-network
    depends_on:
      - app

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: homelab-nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - homelab-network

  db:
    image: mysql:8.0
    container_name: homelab-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-homelab}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-homelab}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - homelab-network

networks:
  homelab-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
