version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelab-app
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ./:/var/www
    networks:
      - homelab-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: homelab-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - homelab-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: homelab-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-homelab}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-homelab}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - homelab-network

networks:
  homelab-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
